"""empty message

Revision ID: 130b285a2e99
Revises: 52d0aab0dec8
Create Date: 2023-11-30 00:59:12.944737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '130b285a2e99'
down_revision: Union[str, None] = '52d0aab0dec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('platform_slug', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('games', 'platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('platform', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('games', 'platform_slug')
    # ### end Alembic commands ###
