"""empty message

Revision ID: 473c0b351c6f
Revises: 130b285a2e99
Create Date: 2023-11-30 01:01:02.793050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '473c0b351c6f'
down_revision: Union[str, None] = '130b285a2e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('platforms', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('games', 'platform_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('platform_name', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('games', 'platforms')
    # ### end Alembic commands ###
