"""empty message

Revision ID: 52d0aab0dec8
Revises: f7aeffbf5e99
Create Date: 2023-11-30 00:58:01.622140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d0aab0dec8'
down_revision: Union[str, None] = 'f7aeffbf5e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('games_slug_key', 'games', type_='unique')
    op.drop_index('ix_game_id', table_name='games')
    op.drop_index('ix_game_slug', table_name='games')
    op.create_index(op.f('ix_games_game_id'), 'games', ['game_id'], unique=False)
    op.create_index(op.f('ix_games_slug'), 'games', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_slug'), table_name='games')
    op.drop_index(op.f('ix_games_game_id'), table_name='games')
    op.create_index('ix_game_slug', 'games', ['slug'], unique=False)
    op.create_index('ix_game_id', 'games', ['game_id'], unique=False)
    op.create_unique_constraint('games_slug_key', 'games', ['slug'])
    # ### end Alembic commands ###
