"""empty message

Revision ID: 891068362161
Revises: 2920c4743ae0
Create Date: 2023-11-20 20:22:43.494022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '891068362161'
down_revision: Union[str, None] = '2920c4743ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registr_at', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'registr_at')
    # ### end Alembic commands ###
