"""empty message

Revision ID: ad3413fe4331
Revises: 473c0b351c6f
Create Date: 2023-11-30 01:05:16.408696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3413fe4331'
down_revision: Union[str, None] = '473c0b351c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('cover', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('release', sa.DateTime(), nullable=True),
    sa.Column('playtime', sa.Integer(), nullable=True),
    sa.Column('platform_slug', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('platforms', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('parent_platform', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('genre', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('avg_rate', sa.Float(), nullable=True),
    sa.Column('completed_count', sa.Integer(), nullable=True),
    sa.Column('wishlist_count', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.Column('esrb_rating', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index(op.f('ix_games_game_id'), 'games', ['game_id'], unique=False)
    op.create_index(op.f('ix_games_slug'), 'games', ['slug'], unique=True)
    op.create_foreign_key(None, 'game_reviews', 'games', ['game_id'], ['game_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'list_games', 'games', ['game_id'], ['game_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_games', 'games', ['game_id'], ['game_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_games', type_='foreignkey')
    op.drop_constraint(None, 'list_games', type_='foreignkey')
    op.drop_constraint(None, 'game_reviews', type_='foreignkey')
    op.drop_index(op.f('ix_games_slug'), table_name='games')
    op.drop_index(op.f('ix_games_game_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
