"""empty message

Revision ID: f7aeffbf5e99
Revises: 2b4f20fad359
Create Date: 2023-11-30 00:51:31.206822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7aeffbf5e99'
down_revision: Union[str, None] = '2b4f20fad359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_game_id', table_name='games')
    op.drop_index('ix_game_slug', table_name='games')
    op.drop_index('ix_games_game_id', table_name='games')
    op.drop_index('ix_games_slug', table_name='games')
    op.create_unique_constraint(None, 'games', ['slug'])
    op.drop_column('games', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'games', type_='unique')
    op.create_index('ix_games_slug', 'games', ['slug'], unique=False)
    op.create_index('ix_games_game_id', 'games', ['game_id'], unique=False)
    op.create_index('ix_game_slug', 'games', ['slug'], unique=False)
    op.create_index('ix_game_id', 'games', ['id'], unique=False)
    # ### end Alembic commands ###
