"""empty message

Revision ID: 07c5b8beee3c
Revises: 32914eca361e
Create Date: 2023-12-18 23:29:44.526234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07c5b8beee3c'
down_revision: Union[str, None] = '32914eca361e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_3', 'games_age_ratings', ['game_id', 'age_rating_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_3', 'games_age_ratings', type_='unique')
    # ### end Alembic commands ###
