"""empty message

Revision ID: 0b9a91ac7f48
Revises: c7b3f455f8e9
Create Date: 2023-12-26 00:19:35.171154

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0b9a91ac7f48'
down_revision: Union[str, None] = 'c7b3f455f8e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'age_ratings',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('type', sa.String(length=100), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('code', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('type'),
    )
    op.create_table(
        'genres',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('name_ru', sa.String(length=100), nullable=True),
        sa.Column('code', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'platforms',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('platform_name', sa.String(length=100), nullable=False),
        sa.Column('platform_slug', sa.String(length=100), nullable=False),
        sa.Column('platform_name_ru', sa.String(length=100), nullable=True),
        sa.Column('code', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('platform_name'),
        sa.UniqueConstraint('platform_slug'),
    )
    op.create_table(
        'age_rating_games',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('game_id', sa.UUID(), nullable=True),
        sa.Column('age_rating_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['age_rating_id'], ['age_ratings.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('game_id', 'age_rating_id', name='unique_age'),
    )
    op.create_table(
        'game_genres',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('game_id', sa.UUID(), nullable=True),
        sa.Column('genre_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('game_id', 'genre_id', name='unique_genre'),
    )
    op.create_table(
        'game_platforms',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('game_id', sa.UUID(), nullable=True),
        sa.Column('platform_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('game_id', 'platform_id', name='unique_platform'),
    )
    op.add_column('users', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_index('ix_users_id', table_name='users')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_column('users', 'user_id')
    op.drop_table('game_platforms')
    op.drop_table('game_genres')
    op.drop_table('age_rating_games')
    op.drop_table('platforms')
    op.drop_table('genres')
    op.drop_table('age_ratings')
    # ### end Alembic commands ###
