"""empty message

Revision ID: 15279e5ca270
Revises: 409569b453ea
Create Date: 2023-12-18 22:37:54.759317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15279e5ca270'
down_revision: Union[str, None] = '409569b453ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games_age_ratings',
    sa.Column('game_id', sa.UUID(), nullable=True),
    sa.Column('age_rating_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['age_rating_id'], ['age_ratings.age_rating_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE')
    )
    op.drop_table('age_rating_games')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_rating_games',
    sa.Column('game_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('age_rating_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['age_rating_id'], ['age_ratings.age_rating_id'], name='age_rating_games_age_rating_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], name='age_rating_games_game_id_fkey', ondelete='CASCADE')
    )
    op.drop_table('games_age_ratings')
    # ### end Alembic commands ###
