"""empty message

Revision ID: 2addc53ca58e
Revises: 2fa401efb3de
Create Date: 2024-01-03 20:44:16.812514

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2addc53ca58e'
down_revision: Union[str, None] = '2fa401efb3de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'activity_types',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('code', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_activity_types_id'), 'activity_types', ['id'], unique=False)
    op.create_table(
        'content_pictures',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('content_id', sa.UUID(), nullable=False),
        sa.Column('picture_path', sa.String(), nullable=False),
        sa.Column('og_picture_path', sa.String(), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_content_pictures_id'), 'content_pictures', ['id'], unique=False)
    op.create_table(
        'like_types',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('code', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_like_types_id'), 'like_types', ['id'], unique=False)
    op.create_table(
        'mailing_types',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('code', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_mailing_types_id'), 'mailing_types', ['id'], unique=False)
    op.create_table(
        'tags',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('code', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table(
        'wall_types',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('code', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_wall_types_id'), 'wall_types', ['id'], unique=True)
    op.create_table(
        'articles',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('wall_id', sa.UUID(), nullable=True),
        sa.Column('parent_post_id', sa.UUID(), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('content', sa.String(), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
        sa.Column('like_count', sa.Integer(), nullable=True),
        sa.Column('slug', sa.String(), nullable=False),
        sa.Column('is_published', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['parent_post_id'], ['articles.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['wall_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_table(
        'blocked_list',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('is_banned', sa.Boolean(), nullable=True),
        sa.Column('report', sa.String(), nullable=True),
        sa.Column('ban_count', sa.Integer(), nullable=True),
        sa.Column('unbanned_day', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'comments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('content_id', sa.UUID(), nullable=False),
        sa.Column('parent_comment_id', sa.UUID(), nullable=True),
        sa.Column('created', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
        sa.Column('like_count', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_table(
        'content_tags',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('content_id', sa.UUID(), nullable=False),
        sa.Column('tag_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_content_tags_id'), 'content_tags', ['id'], unique=False)
    op.create_table(
        'deletion_requests',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('request_day', sa.DateTime(timezone=True), nullable=True),
        sa.Column('delete_day', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'friends',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('follower_id', sa.UUID(), nullable=True),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('status', sa.Boolean(), nullable=True),
        sa.Column('added', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'game_reviews',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('game_id', sa.UUID(), nullable=True),
        sa.Column('created', sa.DateTime(timezone=True), nullable=True),
        sa.Column('grade', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'like_log',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('content_id', sa.UUID(), nullable=False),
        sa.Column('type_id', sa.UUID(), nullable=True),
        sa.Column('value', sa.Boolean(), nullable=True),
        sa.Column('created', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['type_id'], ['like_types.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_like_log_id'), 'like_log', ['id'], unique=False)
    op.create_table(
        'posts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('wall_id', sa.UUID(), nullable=True),
        sa.Column('parent_post_id', sa.UUID(), nullable=True),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
        sa.Column('like_count', sa.Integer(), nullable=True),
        sa.Column('is_published', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['parent_post_id'], ['posts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['wall_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_table(
        'profile_pictures',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('picture_path', sa.String(), nullable=False),
        sa.Column('og_picture_path', sa.String(), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_profile_pictures_id'), 'profile_pictures', ['id'], unique=False)
    op.create_table(
        'user_favorite',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('game_id', sa.UUID(), nullable=True),
        sa.Column('activity_id', sa.UUID(), nullable=True),
        sa.Column('created', sa.DateTime(timezone=True), nullable=True),
        sa.Column('like_count', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['activity_id'], ['activity_types.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'user_games',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('game_id', sa.UUID(), nullable=True),
        sa.Column('activity_id', sa.UUID(), nullable=True),
        sa.Column('created', sa.DateTime(timezone=True), nullable=True),
        sa.Column('like_count', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['activity_id'], ['activity_types.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'user_lists',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('about', sa.String(), nullable=True),
        sa.Column('is_private', sa.Boolean(), nullable=True),
        sa.Column('created', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'user_mailings',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('mailing_id', sa.UUID(), nullable=True),
        sa.Column('created', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['mailing_id'], ['mailing_types.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'walls',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('type_id', sa.UUID(), nullable=True),
        sa.Column('item_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['type_id'], ['wall_types.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'list_games',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('list_id', sa.UUID(), nullable=True),
        sa.Column('game_id', sa.UUID(), nullable=True),
        sa.Column('added', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['list_id'], ['user_lists.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_games')
    op.drop_table('walls')
    op.drop_table('user_mailings')
    op.drop_table('user_lists')
    op.drop_table('user_games')
    op.drop_table('user_favorite')
    op.drop_index(op.f('ix_profile_pictures_id'), table_name='profile_pictures')
    op.drop_table('profile_pictures')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_like_log_id'), table_name='like_log')
    op.drop_table('like_log')
    op.drop_table('game_reviews')
    op.drop_table('friends')
    op.drop_table('deletion_requests')
    op.drop_index(op.f('ix_content_tags_id'), table_name='content_tags')
    op.drop_table('content_tags')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('blocked_list')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_wall_types_id'), table_name='wall_types')
    op.drop_table('wall_types')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_mailing_types_id'), table_name='mailing_types')
    op.drop_table('mailing_types')
    op.drop_index(op.f('ix_like_types_id'), table_name='like_types')
    op.drop_table('like_types')
    op.drop_index(op.f('ix_content_pictures_id'), table_name='content_pictures')
    op.drop_table('content_pictures')
    op.drop_index(op.f('ix_activity_types_id'), table_name='activity_types')
    op.drop_table('activity_types')
    # ### end Alembic commands ###
