"""empty message

Revision ID: 4c30a3d2fa45
Revises: 942b3319ef80
Create Date: 2023-11-30 16:38:58.591390

"""
from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4c30a3d2fa45'
down_revision: Union[str, None] = '942b3319ef80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'my_index', 'games', ['text_tsv'], unique=False, postgresql_using='gin',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('my_index', table_name='games', postgresql_using='gin')
    # ### end Alembic commands ###
