"""empty message

Revision ID: 58bb46af1a2b
Revises: 9cf8627b29ef
Create Date: 2024-01-03 21:00:43.686484

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58bb46af1a2b'
down_revision: Union[str, None] = '9cf8627b29ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('title_tsv', postgresql.TSVECTOR(), nullable=True))
    op.create_index('my_index', 'games', ['title_tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('my_index', table_name='games', postgresql_using='gin')
    op.drop_column('games', 'title_tsv')
    # ### end Alembic commands ###
