"""empty message

Revision ID: 9484d1da685b
Revises: 58bb46af1a2b
Create Date: 2024-01-06 20:32:41.166820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9484d1da685b'
down_revision: Union[str, None] = '58bb46af1a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'profile_pictures', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile_pictures', type_='unique')
    # ### end Alembic commands ###
