"""empty message

Revision ID: a4abad842ab7
Revises: 15279e5ca270
Create Date: 2023-12-18 23:21:32.495326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4abad842ab7'
down_revision: Union[str, None] = '15279e5ca270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friends', 'follower_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('friends', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('game_reviews', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('game_reviews', 'game_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('like_log', 'type_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('list_games', 'list_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('list_games', 'game_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('post_tags', 'post_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('post_tags', 'tag_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_favorite', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_favorite', 'game_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_favorite', 'game_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_favorite', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('post_tags', 'tag_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('post_tags', 'post_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('list_games', 'game_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('list_games', 'list_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('like_log', 'type_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('game_reviews', 'game_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('game_reviews', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('friends', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('friends', 'follower_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
