"""empty message

Revision ID: a5a94b7862d5
Revises: bf8bd5930947
Create Date: 2023-12-11 17:39:58.299557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a94b7862d5'
down_revision: Union[str, None] = 'bf8bd5930947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'age_ratings', ['name'])
    op.create_unique_constraint(None, 'g_tags', ['name'])
    op.create_unique_constraint(None, 'genres', ['name'])
    op.create_unique_constraint(None, 'platforms', ['parent_platform'])
    op.create_unique_constraint(None, 'platforms', ['platform_name'])
    op.create_unique_constraint(None, 'platforms', ['platform_slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'platforms', type_='unique')
    op.drop_constraint(None, 'platforms', type_='unique')
    op.drop_constraint(None, 'platforms', type_='unique')
    op.drop_constraint(None, 'genres', type_='unique')
    op.drop_constraint(None, 'g_tags', type_='unique')
    op.drop_constraint(None, 'age_ratings', type_='unique')
    # ### end Alembic commands ###
