"""empty message

Revision ID: bf8bd5930947
Revises: d82d6475e8f5
Create Date: 2023-12-11 17:15:35.293883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8bd5930947'
down_revision: Union[str, None] = 'd82d6475e8f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('age_ratings', 'name_ru',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('genres', 'name_ru',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('platforms', 'platform_name_ru',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('platforms', 'platform_name_ru',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('genres', 'name_ru',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('age_ratings', 'name_ru',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
