"""empty message

Revision ID: d6c2929601a5
Revises: 10882b207c07
Create Date: 2023-12-15 21:04:46.469317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6c2929601a5'
down_revision: Union[str, None] = '10882b207c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'genre')
    op.drop_column('games', 'platforms')
    op.drop_column('games', 'platform_slug')
    op.drop_column('games', 'parent_platform')
    op.drop_column('games', 'tags')
    op.drop_column('games', 'esrb_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('esrb_rating', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('parent_platform', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('platform_slug', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('platforms', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('genre', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
