"""empty message

Revision ID: d9eef786e25b
Revises: d6c2929601a5
Create Date: 2023-12-15 22:02:29.261440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9eef786e25b'
down_revision: Union[str, None] = 'd6c2929601a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('platform_slug', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('platforms', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('parent_platform', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('genre', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('esrb_rating', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'esrb_rating')
    op.drop_column('games', 'tags')
    op.drop_column('games', 'genre')
    op.drop_column('games', 'parent_platform')
    op.drop_column('games', 'platforms')
    op.drop_column('games', 'platform_slug')
    # ### end Alembic commands ###
