"""empty message

Revision ID: f0ef873cd416
Revises: 
Create Date: 2023-12-12 18:59:55.980470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ef873cd416'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_2', 'game_genres', ['game_id', 'genre_id'])
    op.create_unique_constraint('uix_1', 'game_platforms', ['game_id', 'platform_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_1', 'game_platforms', type_='unique')
    op.drop_constraint('uix_2', 'game_genres', type_='unique')
    # ### end Alembic commands ###
