"""empty message

Revision ID: f79b11634475
Revises: 2addc53ca58e
Create Date: 2024-01-03 20:45:14.047316

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f79b11634475'
down_revision: Union[str, None] = '2addc53ca58e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'esrb_rating')
    op.drop_column('games', 'parent_platform')
    op.drop_column('games', 'platform')
    op.drop_column('games', 'genre')
    op.drop_column('games', 'platform_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'games', sa.Column('platform_name', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True)
    )
    op.add_column('games', sa.Column('genre', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('platform', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column(
        'games', sa.Column('parent_platform', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True)
    )
    op.add_column('games', sa.Column('esrb_rating', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
